demo<-read.csv("demographics.csv")
View(demo)
demo2<-subset(demo,marital == "Married")
View(demo2)
demo2<-subset(demo,marital == "Married" & age > 35)
View(demo2)
demo2<-subset(demo,marital == "Married" & age > 35, select = c(1:3))
View(demo2)
demo2<-subset(demo,marital=="Married" & age<40, select=-c(3:4,8))
View(demo2)
