#join
df1=data.frame(ID=c(1,2,3,4,5),
               w=c('a','b','c','d','e'),
               x=c(1,1,0,0,1),
               y=rnorm(5),
               z=letters[1:5])
df2=data.frame(ID=c(1,7,3,6,8),
               a=c('z','b','k','d','l'),
               b=c(1,2,3,0,4),
               c=rnorm(5),
               d=letters[2:6])
df3=inner_join(df1,df2,by="ID")
df3
left_join(df1,df2,by="ID")
View(mtcars)
mtcars$model<-rownames(mtcars)
first<-mtcars[1:20,]
second<-mtcars[10:32,]
intersect(first,second)
x=data.frame(ID=1:6,ID1=1:6)
y=data.frame(ID=1:6,ID1=1:6)
union(x,y)
union_all(x,y)
   